Challenge_4 in Python 3.5
